<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('project_code_budgets', function (Blueprint $table) {
            $table->id('id_budget');
            $table->string('kode_proyek', 50);
            $table->unsignedBigInteger('id_village');
            $table->string('exp_code', 20)->comment('Expense code, misal: 10101, 20208');
            $table->string('place_code', 50)->index()->comment('Format: [exp_code]-[village_abbr]-01, generated by PHP');
            $table->decimal('budget_usd', 15, 2)->default(0)->comment('Budget dalam USD');
            $table->decimal('budget_idr', 15, 2)->default(0)->comment('Budget dalam IDR');
            $table->decimal('used_usd', 15, 2)->default(0)->comment('Budget terpakai (USD)');
            $table->decimal('used_idr', 15, 2)->default(0)->comment('Budget terpakai (IDR)');
            $table->decimal('exrate', 10, 4)->default(1.0000)->comment('Exchange rate USD to IDR');
            $table->timestamps();

            $table->unique(['kode_proyek', 'id_village', 'exp_code'], 'unique_budget_per_village');
            $table->foreign('kode_proyek')->references('kode_proyek')->on('proyek')->onDelete('cascade');
            $table->foreign('id_village')->references('id_village')->on('villages');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('project_code_budgets');
    }
};